---
title: "Analysis of Vance County EMS Ambulance Distribution"
format: pdf
editor: visual
---

## 1 Background

The Vance County Emergency Medical Services system currently operates four ambulances and two stations with one located in the Southern district and one in the Central district. This configuration led to the residents in the Northern district being under-served with higher average response times than the other two districts. Such delays can lead to critical differences in patient outcomes especially in life threatening emergencies.

In response to this issue and demand for EMS coverage in the North region, Vance county is evaluating the potential of adding a new station in one of the two northern locations: near north or far north station. We use historical EMS call data to make a decision. Each record in the dataset represents one individual emergency trip which includes information like dispatch station, patient location coordinates, and time logs for dispatch, arrival, hospital transport, and clearance.

The main motivation of this analysis is to assess how travel times and system load vary across different station allocation scenarios which are listed in table 1 of the appendix and in particular we aim to answer the two central questions: 1) which of the two possible Northern station locations would better serve the community and 2) how should the four available ambulances be allocated across stations to optimize service coverage and response times.





## 2 Exploratory Data Analysis




## 3 Modeling


## 4 Results


## 5 Conclusion and Future Work

Our analysis showed that relocation to far north resulted in faster response times than near north. We have also shown that it is better to move central ambulances up north than moving the south ambulance and saw that relocating one ambulance from central to far north station reduces response times by about 4%. Therefore from our analysis we saw scenario 4 which is 1 far north, 2 central, and 1 south was the most optimal layout of the 4 ambulances as it reduces the average response time by 4% compared to the baseline of scenario 0.

Some limitations is that our model assumes traffic level to be constant throughout non-vs rush hour. We also are dealing with data that has error introduced by data randomization from the HIPAA protection so there is some marginal error in the distance calculation that stems from this. We are also limited from the smaller sample size and also from the best guess Google API which assumes average conditions.

In the future we can try adding time of day for a random effects which could provide a deeper insight into temporal variation in the response times. We can model this using a continous smooth spline approach using mgcr or poly to capture the nonlinear daily trends without overfitting. We can also try a Bayesian approach to improve interpretability, particularly in regions with fewer calls. Through partial pooling and uncertainty propagation, the use of this approach would allow information sharing across districts while accounting for data sparsity. Finally, a hierarchical modeling approach could be implemented to account for further subdivisions in call type and urgency and this would allow 





## 6 Appendix



| **Scenarios** | **S0 (Current)** | **S1** | **S2** | **S3** | **S4** |
|:--------------|:----------------:|:------:|:------:|:------:|:------:|
| **Far North** | 0 | 0 | 1 | 0 | 1 |
| **Near North** | 0 | 1 | 0 | 1 | 0 |
| **Central** | 3 | 3 | 3 | 2 | 2 |
| **South** | 1 | 0 | 0 | 1 | 1 |


